[theme]
base = "light"
primaryColor = "#2161F9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FC"
textColor = "#172033"
borderColor = "#DDE3EC"
showSidebarBorder = true
chartCategoricalColors = ["#2161F9", "#2161F9", "#53EEEC"]

[theme.sidebar]
primaryColor = "#2563EB"
backgroundColor = "#add3ff"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172033"
borderColor = "#add3ff"